### ISSUE TITLE
cannot handle transparency correctly

### ISSUE THREAD

**Issue by EyMaddis** [matt-way/gifuct-js#1]
Hi,
using the following url in your demo (http://matt-way.github.io/gifuct-js/) will show that transparency is overlaying:
http://cors-anywhere.herokuapp.com/http://i.stack.imgur.com/e8nZC.gif

![image](https://cloud.githubusercontent.com/assets/1409100/17931916/dbe6f18c-6a0d-11e6-9f1c-7787b21ba243.png)

**Comment by matt-way** [comment]
While I could extend the demo to render transparency correctly, the demo is merely there to give you a starting point when building your own renderer. This project is about making it easy for you to extract and parse the internal gif information, not be a go to renderer. This is because everyone has different rendering requirements.

**Comment by rojozabe** [comment]
Good evening, I'm trying to integrate this project into one of my own to get the Frames of a gif specifically. I can't use XMLHttpReader so instead I used a Canvas and embedded the gif to get the base64Image encoding. The issue is that when I try to initialize a Gif object I don't get the Frames arrays and even haven't been able to run the demo locally: When I click Load into any image the container stays white. Also, how can I change those require strings because I need to be able to change the location of the js files and in some cases I would need absolute location. Thanks.

**Comment by EyMaddis** [comment]
@rojozabe please do not hijack Github issues unrelated to your issue.
Despite that here is my advice:
check the JS console, you will probably see an access control ([CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)) issue. To solve this, the server, the images come from, has to set some headers.
In my post above I just prefixed the URL of the image with
http://cors-anywhere.herokuapp.com/

Test it by putting it in front of your image URL and try again.

**Comment by donpark** [comment]
This is what worked for me when rendering frames:

1. Keep track of last frame's `disposalType`.
2. Before rendering frame, `clearRect` if `frameIndex` is `0` or last frame's `disposalType` is `2`.

This makes sense because the term *disposal* implies what to do with output of the frame before rendering the next frame. And when it's the first frame, there is no previous frame so clearing is implicit even if looped back to the first frame.

**Comment by matt-way** [comment]
@jeetiss added a disposal check to a recent pr mentioned, so hopefully this is fixed in the demo, but yeah I do believe this is what was missing.

**Comment by donpark** [comment]
Agreed. `libgif.js` does handle `disposalType: 3` by keeping a copy of the previous full frame but I have yet to see one in-use.
