### ISSUE TITLE
demo/index.html   Out of Memory

### ISSUE THREAD

**Issue by 3400442579** [matt-way/gifuct-js#25]
错误代码: Out of Memory

![bug](https://user-images.githubusercontent.com/34226979/109632036-940fe780-7b81-11eb-82d8-fc9c11f3fbfe.gif)

**Comment by matt-way** [comment]
So I've dug into this GIF, and the problem is that the actual file is corrupted. The last frame just cuts off. However it shouldn't result in an out of mem. The reason this happens is that inside the subblock parser, it is looking for a terminating character which it never receives. The fix I can add is to ensure that the subblocks never read past the end of the stream (in case a terminator is never hit).

**Comment by matt-way** [comment]
Ok, I've pushed a new version that should be able to deal with corrupted gifs in a much nicer way (if the corruption is in the subblocks).
