### ISSUE TITLE
Does the module could a full gif frame size and patch data?

### ISSUE THREAD

**Issue by leogitpro** [matt-way/gifuct-js#42]
Thanks creation so powerful module for decode GIF frames.
But there is a problem for me that the dims attribute not include the full size for a gif. the the patch's item all include the valid colors.
I want a response that include the full size frame even the empty space edge with frame.
We need merge a background image with every frame. the background image size same with gif size.
but now it can't use the patch's data directly in OpenCV.js. It's need same size picture to merge.
Thanks a lot.

**Comment by matt-way** [comment]
The reason that I separated out the `decompressFrames()` function is because it makes assumptions about image dims and the like. This allows you to build your own frame decompressor should you feel the need. If you look at the source for `decompressFrames` you should be able to modify it to your needs.
